### ISSUE TITLE
Can this be used to load a Vue single file component?

### ISSUE THREAD

**Issue by ckaczor** [JounQin/vue-dynamic#2]
The documentation seems to hint at this but can this be used to dynamically load/use a template from a .vue file?  Do you have an example for that?

I'm hoping to load a component asynchronously from an external .vue file but haven't worked out how to do it yet.

Thanks!

**Comment by JounQin** [comment]
Oh, sorry, but it's not designed to do that.

It seems not a good idea to use *.vue* in browser which need to process something like *less, sass, stylus, es6* and they should be processed in backend.

IMO, you should compile you *.vue* file to normal js codes before you store them into DB with *rollup-plugin-vue* or *vue-loader* or even *vuerify* so that you will be able to load them asynchronously.

Or, if you're not storing temples in DB then you should just use webpack or something alse for code splitting.

Hope it helps.😀

**Comment by ckaczor** [comment]
Thanks for the reply.  For my case I'm trying to load the component via HTTP from another location rather than from a database but I think the concept is more or less the same?

I initially tried this using the JS file created by webpack code-splitting but I haven't figured out how to get Vue to load it after I've retrieved it via HTTP.

Can vue-dynamic load the component from the JS string?  Is there an example?  I think if I had an example of loading it from the code-split JS string I can make it work with the string/file via HTTP.

Thanks again!

**Comment by JounQin** [comment]
Sorry I was a little busy there days.

And sorry again for that `vue-dynamic` maybe could not meet your requirement, because I think it is not a good idea to load and execute a script text rather than use normal script tag.

It may need to use evil `eval` or another custom module system to load external dependencies which is indeed unnecessary for me.

I'm really wondering why you are not using normal building tools.

`vue-dynamic` is used to store static template/methods into DB which has been declared in *README.md*.

Besides, if you could load scripts via HTTP, then why not just use script tag and use the HTTP link as source.
